#!/bin/bash

ACSDIR=/etc/acs/

if [ "$(id -u)" -ne 0 ]; then
	echo 'Please run as root or using sudo.'&>2
	exit 1
fi

if [ -d $ACSDIR ]; then
	echo "ACS is not installed. Please execute install.sh first"&>2
	exit 1
fi

if [ "$#" -ne 2 ]; then
	echo "Please check the parameters." &>2
	exit 1
fi

if [[ ! $1 =~ ^[+-]?[0-9]+\.?[0-9]*$ ]];then
	echo "Please check the parameters. The price is not float value." &>2
	exit 1
fi

cd $ACSDIR

sqlite3 -batch vminfo.db "SELECT NAME FROM VM WHERE PRICE < $1 AND STATUS = 'RUN_SPOT';" | while read -r name ;do
	#hibernate it
	if [ sqlite3 -batch vminfo.db "UPDATE VM SET STATUS = 'READY_SPOT' WHERE NAME = '$name';" ];then
		echo "Error in saving DB with name $name." &>2
	fi
done

sqlite3 -batch vminfo.db "SELECT NAME FROM VM WHERE PRICE >= $1 AND STATUS = 'READY_SPOT';" | while read -r name ;do
	#wake it up
	if [ sqlite3 -batch vminfo.db "UPDATE VM SET STATUS = 'RUN_SPOT' WHERE NAME = '$name';" ];then
		echo "Error in saving DB with name $name." &>2
	fi
done

exit 0
